//
//  WFBikePowerDelegate.h
//  WFConnector
//
//  Created by Michael Moore on 7/26/12.
//  Copyright (c) 2012 Wahoo Fitness. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <WFConnector/_WFBikePowerDelegate.h>
#import "WFCPMCalibrationResponseObject.h"
#import "wf_bike_trainer_types.h"


/**
 * Provides the interface for callback methods used by the WFBikePowerConnection.
 *
 * This delegate handles callbacks for commands according to the CSC Profile.  For
 * commands used by Wahoo-specific trainer devices, such as the KICKR, please see
 * the WFBikeTrainerDelegate.
 */
@protocol WFBikePowerDelegate <_WFBikePowerDelegate>

@optional

/**
 * Invoked when a response to the Manual Zero command is received.
 *
 * @param cpmConn The WFBikePowerConnection instance.
 * @param ucStatus The command status code (1 for Success).
 * @param errorParam optional param for some command status
 * @param usOffset The offset generated by the calibration command.
 * @param scTemp The temperature read by the calibration command.
 */
- (void)cpmConnection:(WFBikePowerConnection*)cpmConn didReceiveCalibrationResponse:(WFCPMCalibrationResponseObject*) responseObject;
- (void)cpmConnection:(WFBikePowerConnection*)cpmConn didReceiveCalibrationResponse:(UCHAR)ucStatus offset:(USHORT)usOffset temperature:(SCHAR)scTemp __attribute__((unavailable("Use: cpmConnection:didReceiveCalibrationResponse:errorParam:forceOffset:manufactureData:offset:temperature")));
- (void)cpmConnection:(WFBikePowerConnection*)cpmConn didReceiveCalibrationResponse:(UCHAR)ucStatus offset:(SSHORT) offfsetCompensation __attribute__((unavailable("Use: cpmConnection:didReceiveCalibrationResponse:errorParam:forceOffset:manufactureData:offset:temperature")));


/**
 * Invoked when a response to the Set Crank Length command is received.
 *
 * @param cpmConn The WFBikePowerConnection instance.
 * @param ucStatus The command status code (1 for Success).
 */
- (void)cpmConnection:(WFBikePowerConnection*)cpmConn didReceiveSetCrankLengthResponse:(UCHAR)ucStatus;

/**
 * Invoked when a response to the Read Crank Length command is received.
 *
 * @param cpmConn The WFBikePowerConnection instance.
 * @param ucStatus The command status code (1 for Success).
 * @param crankLength The crank length, in meters.
 */
- (void)cpmConnection:(WFBikePowerConnection*)cpmConn didReceiveReadCrankLengthResponse:(UCHAR)ucStatus crankLength:(float)crankLength;

@end

